styleguide: stride-nyc/remote_retro
engines:
  fixme:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
  remark-lint:
    enabled: false
exclude_paths:
- config
- priv/repo
- test

